### ISSUE TITLE
Request for an accented font

### ISSUE THREAD

**Issue by pepe59** [widapro/wledPixel#11]
In my country (Czech Republic) we use the alphabet with diacritics Á, á, Č, č, É, é, ě, Š, š, etc.
Is it possible to add a character set with diacritics?

**Comment by widapro** [comment]
It is possible. But I don't have Czech font for display. 
It would be great if you took one of the already existing fonts as a basis and added the necessary elements for the characters of the Czech alphabet in a graphic editor.

You can easily do it on this site: https://pjrp.github.io/MDParolaFontEditor

Import one of the existing fonts, for example I like the **wledFont_cyrillic** font. Just copy lines 529 to 786 https://github.com/widapro/wled-pixel-v2/blob/main/lib/wledFont/wledFont.h#L529-L786
and paste in the box on the left and click the **Import** button. Once you're done **Export** everything back and post it as a text file here.

**Comment by pepe59** [comment]
Thanks. I will try to make accented letters.
I will post them here.
