### ISSUE TITLE
Topic incorrect

### ISSUE THREAD

**Issue by martusi61** [widapro/wledPixel#12]
I installed v.2.3 and changed the "MQTT zone text topic" which for the "Zone" works regularly, but when I used it with the topic "intensity" it doesn't do anything, I had to reset the "MQTT device prefix" by default. For the rest, great work.

**Comment by widapro** [comment]
Should be fixed in v2.6 Please check it: https://github.com/widapro/wledPixel/releases/tag/v2.6

**Comment by martusi61** [comment]
Fine
