### ISSUE TITLE
Zone 0 gets wiped

### ISSUE THREAD

**Issue by sirpilz** [widapro/wledPixel#17]
Firstly thanks for your work.

I have two displays working with two wemo d1s. Both running firmware 2. Same power supplies. One of them works perfectly. The other one stops working and when i login it has no zones set everytime. I go back set zone 0 and it works again for a random period of time and then does the same thing. It doesnt reboot it just loses zone setting. I have resoldered wires incase of that being the issue but it has not fixed the problem.

Any idea what this might be?  I did try the latest firmware but it didnt seem to fix the issue.

**Comment by widapro** [comment]
How many zones are in use?
What are the operating modes for each zone?

It looks like the device is rebooting due to lack of memory. Or the device is damaged. If possible, try replacing the ESP module on the problem device.

**Comment by sirpilz** [comment]
I swapped wemo for another and no problem so was faukty hardware. Thanks can close.
