### ISSUE TITLE
Cannot set 2 zones one one 4 element display

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#2]
If I try to setup 2 zones on a 4 segment display only zone0 works.
It keeps reverting to 4 and 7 on zone 1

![image](https://user-images.githubusercontent.com/20055899/172958734-a8cba00a-ba80-4571-9919-38036f4df671.png)

![image](https://user-images.githubusercontent.com/20055899/172958871-20f52afa-239e-472a-84c4-df24a94b4ea4.png)

**Comment by widapro** [comment]
This issue should have been fixed in previous releases. Isn't it?

**Comment by widapro** [comment]
The issue has been resolved in last releases and is no longer reproduced.
