### ISSUE TITLE
control brighness by home assistant not working

### ISSUE THREAD

**Issue by dddesign** [widapro/wledPixel#20]
if I configure wledPixel with my mqtt server I'll get a control element in home assistant for brightness. but changing values has no effect. is this as it should be? by publishing mqtt topic for brighntess it's working...
thanks for any tips and thank you for this great project!

**Comment by widapro** [comment]
Try new release, I did several changes with brightness: https://github.com/widapro/wledPixel/releases/tag/v2.5
Brightness control in HA should works.

**Comment by dddesign** [comment]
thanks, I update to version 2.5, but still the same: can't set brightness by home assistant!
also all configuration setting are not working (should they?), see screenshot

could it be that the problem is based on my old HA version? I use core-2021.11.3 and OS Version 6.6

![Bildschirmfoto 2022-10-18 um 23 31 31](https://user-images.githubusercontent.com/780871/196548869-be7f025d-ee9d-4286-908f-563e1a65552f.png)

**Comment by martusi61** [comment]
I would update immediately. Pay attention to the compatibility of the old HA configuration with the latest version.

**Comment by widapro** [comment]
@dddesign Is the problem actual on the latest versions of HA?

**Comment by widapro** [comment]
Should works without issues. Well tested in v2.6 and Home Assistant 2023.09.02
Please check it: https://github.com/widapro/wledPixel/releases/tag/v2.6
