### ISSUE TITLE
open weather doesnt work

### ISSUE THREAD

**Issue by sommo** [widapro/wledPixel#22]
Hi @widapro ! really amazing project, i'm still using since the first version and now i'm trying your new one, seems really super but when trying to use the openweather dashboard after reboot report it as "manual" like it doesn't "like" it... any ideas?
tried to put in different zone, i get to work it only one time, with temperature.
Thank you

**Comment by widapro** [comment]
Let's continue the discussion here: https://github.com/widapro/wledPixel/issues/24
Try the new beta version from the link above. It also contains some changes in working with OpenWeather.
