### ISSUE TITLE
lost layout and setting after reboot

### ISSUE THREAD

**Issue by sommo** [widapro/wledPixel#23]
Hi wida! once rebooted (from button on wemos) or when powering it off the wemos came up with the right zone but in manual mode.
mqtt data (are storage expect the server ip), so it need to be inserted again.
Did i flashed it wrong? or is a know issue?
thank you

**Comment by widapro** [comment]
Let's continue the discussion here:: https://github.com/widapro/wledPixel/issues/24
Try the new beta version from the link above
