### ISSUE TITLE
Change mode by MQTT not working 

### ISSUE THREAD

**Issue by hungquangtdh2** [widapro/wledPixel#28]
Hi developer. Thank for your software
I face to an issue that MQTT from Home assistant cannot change the work mode. 
service: mqtt.publish
data:
  topic: wledPixel-7FF2/zone0/workMode 
  payload: manualInput
It not change anything on Wled

**Comment by ljpyro** [comment]
I have the same issues. 

running 2.5.1beta


The only things are working are the following topics:

Intensity and MQTT text. 

Everything else is not working. 

i'm also missing zone3 ( only 3 zones available )

I love the software, thanks for sharing

**Comment by widapro** [comment]
@hungquangtdh2 it was a mistake in the documentation with workmode topic. Please send MQTT message to the topic: (workmode without capital M): devicePrefix/zoneN/**workmode**
In your example it should be:
`topic: wledPixel-7FF2/zone0/workmode`

I will fix the documentation in the next version.

**Comment by widapro** [comment]
@ljpyro Please check out this version: [wledPixel-v2.5.2b_WeMos_D1_mini.esp8266.bin.zip](https://github.com/widapro/wledPixel/files/10810232/wledPixel-v2.5.2b_WeMos_D1_mini.esp8266.bin.zip)

I tested it out and all MQTT topics work for me.

**Comment by ggaljoen** [comment]
Great Project, thank you!
I saw overhere one of your most recent activity and a beta version of 2.5.2b and 3b
@widapro do you plan any further development/release?

**Comment by widapro** [comment]
@ggaljoen Yes, a new release was published today.
Please check it: https://github.com/widapro/wledPixel/releases/tag/v2.6
