### ISSUE TITLE
Reboot on sentence

### ISSUE THREAD

**Issue by martusi61** [widapro/wledPixel#29]
Via mqtt I send the titles of the home assistant notifications to my wled v.2.4, but some sentences cause the Wemos D1 Mini in use to restart. I did a lot of tests, for example, the sentence "Correzione sospensione schermo HuaweP30Mau" works correctly, while if I add an "i" to Huawei and send "Correzione sospensione schermo HuaweiP30Mau" its reboot!

**Comment by widapro** [comment]
There was a 50 symbols limit for incoming messages. I doubled this value in v2.6

Please check it: https://github.com/widapro/wledPixel/releases/tag/v2.6

**Comment by martusi61** [comment]
Ok fine, installed
