### ISSUE TITLE
2 things

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#3]
This is great !
the website for this thing is slick

#1 I think it would be nice to have the ip address to continue to scroll at startup.
#2 I closed too many tabs.  What is the link for communit.homeassistant where I found this and posted?  I figured out how to post my temps to mqtt and wanted to add it.

Thanks,
Grey

**Comment by widapro** [comment]
After a detailed study of your proposal, I found out that the constant display of the IP address after switching on will block the main functionality of the device. Therefore, the IP address will be shown once on boot. If you missed it then you can always reboot your device and see the IP address again.
All I could do was slightly increase the display time of the IP address on the screen.
