### ISSUE TITLE
Warning after HA update

### ISSUE THREAD

**Issue by pepe59** [widapro/wledPixel#32]
After updating HAOs version 2023.8 I got this warning. Is there any solution?
![warování wledpixel](https://github.com/widapro/wledPixel/assets/61280529/36d03efd-e291-42ee-bcf0-5a8bf1c1ec7a)
![varovani wledpixel temperature](https://github.com/widapro/wledPixel/assets/61280529/849ecda1-9919-4dcd-bf03-e2c76e3cf4c2)

**Comment by widapro** [comment]
Fixed in v2.6 Please check it: https://github.com/widapro/wledPixel/releases/tag/v2.6
