### ISSUE TITLE
WallClock precision

### ISSUE THREAD

**Issue by martusi61** [widapro/wledPixel#35]
I noticed that the WallClock loses precision after a few days which accumulates over time, upon restarting it synchronizes with the NTP and returns to showing the correct time.

**Comment by ljpyro** [comment]
I noticed exactly the same problem. Would be nice if it synchronizes every 6 hours with NTP.

**Comment by mats-nk** [comment]
From what I can see the time get updated at startup, when config changes is made and if MQTT is disconnected.

Suggestion: Update NTP and OWM at the same time,

So just include `timeClient.update();` in the `// OWM update` part and remove it from the MQTT disconnect part.

**Comment by widapro** [comment]
I added settings for NTP server and NTP update interval in [v.2.6.1](https://github.com/widapro/wledPixel/releases/tag/v2.6.1)
<img width="866" alt="Screen Shot 2023-09-30 at 00 14 48" src="https://github.com/widapro/wledPixel/assets/6948905/8a087665-d12e-486f-b2c4-bcaa0f19ee33">

**Comment by martusi61** [comment]
Great!

**Comment by ljpyro** [comment]
Fantastic. 

Thank you.
