### ISSUE TITLE
MQTT client issue

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#38]
So I noticed in the serial monitor when I shut down HA that it was giving an MQTT error ever 5 seconds even though none of the work modes were set to it

I unchecked use it and the errors went away.

I think the tickbox use should not be required.  As in if a zone was set to it, enable it.  Otherwise I think it is creating too much overhead checking every 5 seconds if it is not needed?

Thanks,
Grey

**Comment by widapro** [comment]
MQTT is used not only to display data for the display, but also to control the display regardless of the work mode of the zones. Thats why MQTT settings required "Enable checkbox".

**Comment by Grey-Lancaster** [comment]
OK, thanks
