### ISSUE TITLE
Temp Sensor

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#39]
I am having problems with the temp sensor.  It always reads the temp on a reboot, but the it is it or miss?

Thanks,
Grey

*WM: AutoConnect Try No.:
*WM: 0
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 192.168.1.180
Wifi connected to SSID: shop2
Local ip: 192.168.1.180
Gateway: 192.168.1.1
Subnet: 255.255.255.0
DNS: 192.168.1.1
HostName: wledPixel-5AAE
MQTT Device Prefix: wledPixel-5AAE

zone0 Message availabel: 8888

zone0 Message availabel: ip: 192.168.1.180
Init configuration
ds18b20 measurement temperature: 73.8 F
zone0 Message availabel: 73.8°F

ds18b20 measurement temperature: 73.7 F
zone0 Message availabel: 73.7°F
ds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperature
ds18b20 measurement temperature: 74.3 F
zone0 Message availabel: 74.3°F
ds18b20 Error getting temperatureds18b20 Error getting temperatureds18b20 Error getting temperature

**Comment by widapro** [comment]
Should be fixed in [2.6.1](https://github.com/widapro/wledPixel/releases/tag/v2.6.1). Please check.
