### ISSUE TITLE
Temp is not an option in HA Deices

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#42]
Just curious. Should the ds18b20 show here?

![image](https://github.com/widapro/wledPixel/assets/20055899/5d1af545-6ae2-4602-98d6-24b5999ba425)

**Comment by widapro** [comment]
fixed in[ v.2.6.1](https://github.com/widapro/wledPixel/releases/tag/v2.6.1)
<img width="315" alt="Screen Shot 2023-09-30 at 00 11 50" src="https://github.com/widapro/wledPixel/assets/6948905/b0f5d6eb-47c6-4474-8165-64ccd044ec40">
