### ISSUE TITLE
DS18b20 temp not published

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#48]
I guess this is supposed to do it, but it never shows the temp

          if (mqttEnable) mqttClient.publish(String("wledPixel-" + shortMACaddr + "/temperature").c_str(), dsTemp.c_str());

![image](https://github.com/widapro/wledPixel/assets/20055899/5d23eb4d-65d3-4ca8-9111-172241a2d07e)

**Comment by mats-nk** [comment]
That is NOT the internal temperature, its the External Dallas OneWire DS18B20 temp sensor.

**Comment by Grey-Lancaster** [comment]
I did not say it was the internal temp. There is no internal temp?
The code says to publish    dsTemp.c_str());

**Comment by Grey-Lancaster** [comment]
not sure what the diff is but other builds have made a lot more entities tan now.  Not sure if it is "breaking" at setting the temp

![image](https://github.com/widapro/wledPixel/assets/20055899/fb76cd9e-1c3a-4ec8-8626-efaec67e1aad)

\
vs

![image](https://github.com/widapro/wledPixel/assets/20055899/43e5836a-01fd-407c-a1e7-c84f959c7ae4)

**Comment by Grey-Lancaster** [comment]
Broken

**Comment by widapro** [comment]
It was a change in Home Assistant MQTT discovery for sensor. I fixed it in [v2.7.1](https://github.com/widapro/wledPixel/releases/tag/v2.7.1)
