### ISSUE TITLE
wallclock reboots 

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#49]
I am having problems with the wall clock rebooting when I switch to it or apply to the NTP settings.
I see sometimes I get an error that the NTP time could not be updated.
Is there a wait time for it to sync or would it crash if it did not sync?

Soft WDT reset

Exception (4):
epc1=0x40100254 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: sys
sp: 3fffeb20 end: 3fffffb0 offset: 0160

on boot sometimes:
Gateway: 192.168.1.1
Subnet: 255.255.255.0
DNS: 192.168.1.1
HostName: wledPixel-5AAE
MQTT Device Prefix: wledPixel-5AAE

**ERROR: NTP time synchronization failed**
zone0 Message availabel: 8888

zone0 Message availabel: ip: 192.168.1.180
Init configuration
ds18b20 measurement temperature: 76.2 F

**Comment by widapro** [comment]
Should be fixed in [wledPixel v2.7](https://github.com/widapro/wledPixel/releases/tag/v2.7)
