### ISSUE TITLE
Show the IP at first boot

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#51]
On your first version when a fresh install or reboot it showed the ip and stayed there.  Now it flips to manual.
I think it would be best to stay on the ip until connected to the settings page or changes were made. (or at least change the time to show the ip longer)

And I would rather see the default config use all 4 matrix instead of three :_)

Yea yea yea, I know. I am queer, but I am using it !!

**Comment by widapro** [comment]
I added a 5-second delay to keep the IP address on the screen. That should be enough from my point of view.
I updated the default settings based on your suggestion and now 4 matrix have been used by default.
[wledPixel v2.7](https://github.com/widapro/wledPixel/releases/tag/v2.7)

**Comment by Grey-Lancaster** [comment]
Thanks, all is well now
