### ISSUE TITLE
Temperature missing

### ISSUE THREAD

**Issue by martusi61** [widapro/wledPixel#52]
I have been using version v2.6.1 for a long time, And apart from a few reboots and slowdowns in mqtt texts it worked fine, but a few days ago the home assistant temperature feature became unavailable. I checked the configuration page and the temperature was right It was indicated . I therefore deleted the entity from home assistant hoping for its restoration, but without success. Today I installed the new version 2.7, but still no success. How can I reset the temperature in home assistant of my wledpixel sensor?

**Comment by Grey-Lancaster** [comment]
Well it is getting published but I have no clue how to correct it

![image](https://github.com/widapro/wledPixel/assets/20055899/2a73099e-a6d7-49ae-9ce7-1c24fe57ae0b)

**Comment by widapro** [comment]
You can delete the whole device in HA and restart wledPixel. The device will publish an auto-discover message once after booting and connecting to MQTT

**Comment by martusi61** [comment]
> Puoi eliminare l'intero dispositivo in HA e riavviare wledPixel. Il dispositivo pubblicherà un messaggio di rilevamento automatico una volta dopo l'avvio e la connessione a MQTT

Thanks so much, but I did that and got nothing, HA recreated all the entities except the temperature one 
![Screenshot_20231114-235011~2](https://github.com/widapro/wledPixel/assets/51626288/475ecc6a-e07f-4d21-a023-d342e6e8d942)

**Comment by Grey-Lancaster** [comment]
same here.  deleted and it recreates but does not have the temp, As I said the value does show up in mqtt explorer there is just not an entity for it

![image](https://github.com/widapro/wledPixel/assets/20055899/5c9d1c19-ee2a-467c-9500-4c27e615dbc1)

![image](https://github.com/widapro/wledPixel/assets/20055899/312bd297-e599-44ec-8d5b-ceb493cd82d2)

![image](https://github.com/widapro/wledPixel/assets/20055899/5063cc94-f03a-48d6-ba97-9db7f4c4e3e1)

**Comment by Grey-Lancaster** [comment]
I cannot figure it out.  I have been fingering with it for 2 days.  The temp is pushed to MQTT but there is no matching topic?

**Comment by widapro** [comment]
It was a change in Home Assistant MQTT discovery for sensor. I fixed it in [v2.7.1](https://github.com/widapro/wledPixel/releases/tag/v2.7.1)

**Comment by martusi61** [comment]
2.7.1 version it's ok for me
