### ISSUE TITLE
ESP32 board

### ISSUE THREAD

**Issue by Grey-Lancaster** [widapro/wledPixel#53]
What esp32 board are you using for battery? Adafruiut feather?
The wemsos 8266 board has a battery shield also.

https://www.wemos.cc/en/latest/d1_mini_shield/battery.html

**Comment by widapro** [comment]
I use Wemos D1 Mini ESP32 – ESP-WROOM-32 / 4MB

**Comment by TonnieKlappe** [comment]
How to upload the files to the wemos D1?

**Comment by Grey-Lancaster** [comment]
Download the bin file and use esphome flasher 
https://web.esphome.io/?dashboard_wizard
