### ISSUE TITLE
Control effects

### ISSUE THREAD

**Issue by martusi61** [widapro/wledPixel#6]
Thanks for your work, I really appreciate it. I had already used the old version of wLed, now I'm trying the new one but i noticed that the controls and effects no longer work, maybe the keywords have changed? I can only set effects for all texts directly from the web interface, but I need to alternate as I publish via mqtt. Thanks in advance for your reply.

**Comment by upstairs-at-erics** [comment]
same problem here with devicePrefix/zoneN/scrolleffect.
Single zone 0,   0 to 11 modules
can't set effect

Sending this 
          data:
            topic: 3420/zone0/scrolleffect_without_exit
            payload: blinds

displays the message 'MQTT' which suggests an error in the message?

**Comment by martusi61** [comment]
> stesso problema qui con devicePrefix/zoneN/scrolleffect. Singola zona 0, da 0 a 11 moduli non possono impostare l'effetto
> 
> Invio di questi dati: topic: 3420/zone0/scrolleffect_without_exit payload: blinds
> 
> visualizza il messaggio 'MQTT' che suggerisce un errore nel messaggio?

In the meantime some firmware updates have come out, now it works!

**Comment by upstairs-at-erics** [comment]
strange, i’m using latest release 2.2.1 and its not working. I’ve tried publishing the command a number of different ways (HA, MQTT manager etc) and anything with zone0 in it doesn’t seem to work. Just causes ‘mqtt’  to scroll across the panel.

**Comment by martusi61** [comment]
> strano, sto usando l'ultima versione 2.2.1 e non funziona. Ho provato a pubblicare il comando in diversi modi (HA, MQTT manager ecc.) E qualsiasi cosa con zone0 non sembra funzionare. Fa semplicemente scorrere 'mqtt' sul pannello.

Try PA_BLINDS in payload

**Comment by upstairs-at-erics** [comment]
that's it! thank you so much. I feel real dumb now. :-)

**Comment by martusi61** [comment]
Don't worry, it happened to me too, I thought about it for a while and then I solved it. Glad to have helped you.

**Comment by widapro** [comment]
To prevent happened it with others I added the list of supported effects in README and in the info column on the device settings page.
