### ISSUE TITLE
MQTT Server goes crazy

### ISSUE THREAD

**Issue by djalexz** [widapro/wledPixel#9]
Hi and thank you for your great project.
My Problem:

When I enable the MQTT server in iobroker and connect to WLED, the log of iobroker goes crazy and the WLED software continuously gets requests or states sent via MQTT.

Settings of iobroker MQTT Server:

![image](https://user-images.githubusercontent.com/11389551/177742072-48863ce3-4dbf-4b26-9e5e-646ed954e613.png)

![image](https://user-images.githubusercontent.com/11389551/177742199-366fec29-88f2-46e1-bede-f2d362494135.png)

Log goes crazy:

![image](https://user-images.githubusercontent.com/11389551/177755325-4d7aec12-cda8-40a5-acb7-05fc811a3de1.png)

Log from ESP goes crazy too:

![image](https://user-images.githubusercontent.com/11389551/177755426-6bffff56-9566-4dd6-b129-ea6b77b18507.png)

What am I doing wrong?

Thanks a lot

**Comment by capitaenz** [comment]
I have the same problem. What information can I contribute?
No proper function possible with ioBroker.

**Comment by capitaenz** [comment]
The bug seems to have been fixed with version 2.5. thanks!
